config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'


  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  resources :feeds
  resources :entries
	root 'entries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
    belongs_to :feed
    self.per_page = 10
end

app/models/feed.rb
class Feed < ApplicationRecord
has_many :entries, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    get_and_show_entries
  end

  def index_with_button
    get_and_show_entries
  end

  def show
    @entry = Entry.find_by_id(params[:id])
  end



  private

  def get_and_show_entries
    @entries = Entry.paginate(page: params[:page], per_page: 15).order('created_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render(:status => 404)
  end

  def internal_server_error
    render(:status => 500)
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :load_entries, :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all

  end

  def load_entries
    @entries ||= Entry.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    @entry = Entry.new
    @feed = Feed.find(params[:id])
  #  @result = Feedjira::Feed.fetch_and_parse "#{@feed.url}"

    require 'rss'
    @rss = RSS::Parser.parse("#{@feed.url}",false)
 #   puts "ceci est le resultat",@rss
=begin
    puts result.title
    puts result.url
    puts result.description
      # puts result.entries
  #  @entry = @feed.entry



    @entry.feed_id = @feed.id
   @entry.pulished = DateTime.now
    @entry.content = result.description
    @entry.title = result.title


      #  @entry_feed_id = @feed_id
      # puts "entry title",@entry_title
      #  puts "entry description",@entry_description
   # puts result
   # puts "entry feed id",@entry_feed_id
   # puts "het el kol ","#{result.entries}"

#   @entry.save
    Rails.logger.info(@entry.errors.inspect)

=end
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)
    require 'rss'

    urlentite = feed_params[:url]
    puts "ceci est le lien ",urlentite




    respond_to do |format|
      if @feed.save
        format.html { redirect_to :controller => 'entries', :action => 'index' , notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end

    puts "ceci est le feed ID",@feed.id
    rss = RSS::Parser.parse(urlentite,false)
    rss.items.each do |item|
      puts "ceci est item title ",item.title
      @entry = Entry.new
      @entry.title = item.title
      @entry.content = item.description
      @entry.feed_id = @feed.id
      @entry.pulished = item.date
      @entry.url = item.link
      @entry.save
      Rails.logger.info(@entry.errors.inspect)
    end


  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:name, :url)
    end
    def entry_params
      params.require(:entry).permit(:content, :title, :feed_id,:pulished,:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/entries/_entry.html.erb
<div>
  <h2><%= link_to entry.title, entry_path(entry) %></h2>

  <small><em><%= entry.pulished %></em></small>

  <p><%= truncate(strip_tags(entry.content), length: 600) %></p>
</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :entry_title %>
  </div>

  <div class="field">
    <%= form.label :pulished %>
    <%= form.text_field :pulished, id: :entry_pulished %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :entry_content %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :entry_url %>
  </div>

  <div class="field">
    <%= form.label :lu %>
    <%= form.text_field :lu, id: :entry_lu %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<div class="btn btn-primary">
  <%= link_to 'Nouveau Flux', new_feed_path,  {:style=>'color:#FFFFFF;', :class => "css_class"} %>
</div>
<div class="page-header">
  <h1>Mes Flux RSS</h1>
</div>

<div id="static-pagination">
  <%= will_paginate %>
</div>

<div id="my-entries">
  <div class="page-delimiter first-page" data-page="<%= params[:page] || 1 %>"></div>
  <%= render @entries %>
</div>

<% if @entries.next_page %>
  <div id="infinite-scrolling">
    <%= will_paginate %>
  </div>
<% end %>

app/views/entries/index.js.erb
$('#my-entries').append('<%= j render @entries %>');
<% if @entries.next_page %>
$('.pagination').replaceWith('<%= j will_paginate @entries %>');
<% else %>
$(window).off('scroll');
$('.pagination').remove();
<% end %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titre: </strong>
  <%= @entry.title %>
</p>

<p>
  <strong>Publié le: </strong>
  <%= @entry.pulished %>
</p>

<p>
  <strong>Contenu: </strong>
  <%= @entry.content.html_safe %>
</p>

<p>
  <strong>Lien: </strong>
  <%= @entry.url %>
</p>

<p>
  <% if @entry.lu %>
  lu
  <% else %>
non lu
  <% end %>
</p>

<div class="btn btn-danger">
  <%= link_to 'Accueil', entries_path,  {:style=>'color:#FFFFFF;', :class => "css_class"} %>
</div>

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :feed_name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :feed_url %>
  </div>


  <div class="actions">
    <%= form.submit "ok" %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.name %></td>
        <td><%= feed.url %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>Ajouter un Flux</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @feed.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>


<% @rss.items.each do |item| %>
  <b><%= item.title %> </b>
  <p><%= item.description.html_safe %> </p>
  <%= item.date %>
  <br>

<% end %>
<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>InfiniteScrolling</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">
  <%= yield %>
</div>


</body>
</html>